### ISSUE TITLE
change github pages source branch

### ISSUE THREAD

**Issue by HotelCalifornia** [gwijthoff/phillycommunitywireless#3]
I was experimenting with automating the build and deploy process for this site (see 8ba2070, d79487c, 889ac4e), and part of the process is to deploy to a branch other than master--- `gh-pages`.

@gwijthoff can you change the source branch to `gh-pages`? I don't have admin access to this repo, so I can't change the setting myself 😖

**Comment by gwijthoff** [comment]
@HotelCalifornia done! Looks great Alex, thanks for setting up gh actions. Definitely a much cleaner solution.
